import { IProduct } from '../components/Product';

export const products: Array<IProduct> = [
	{
		id: '1',
		name: 'Túi Messenger Monogram Carlos',
		category: 'Bag',
		description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, possimus nostrum!',
		price: 100,
		imageURL: 'https://www.leonardo.vn/cdn/shop/files/DSCF6782_700x.jpg?v=1698297502',
		buyQuantity: 0,
		remainingQuantity: 10,
	},
	{
		id: '2',
		name: 'Product 2',
		category: 'Bag',
		description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, possimus nostrum!',
		price: 200,
		imageURL: 'https://www.leonardo.vn/cdn/shop/files/1_9ba404ad-424e-494e-a88b-b06637a97975_700x.jpg?v=1697304023',
		buyQuantity: 0,
		remainingQuantity: 10,
	},
	{
		id: '3',
		name: 'Product 3',
		category: 'Bag',
		description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, possimus nostrum!',
		price: 300,
		imageURL: 'https://www.leonardo.vn/cdn/shop/files/TuiH_pCarlosTh_ngHi_uLeonardo01_700x.jpg?v=1695789900',
		buyQuantity: 0,
		remainingQuantity: 10,
	},
	{
		id: '4',
		name: 'Product 4',
		category: 'Bag',
		description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, possimus nostrum!',
		price: 400,
		imageURL: 'https://www.leonardo.vn/cdn/shop/files/TuidanamVincenzoTh_ngHi_uLeonardo01l_n_700x.jpg?v=1683540385',
		buyQuantity: 0,
		remainingQuantity: 10,
	},
	{
		id: '5',
		name: 'Product 5',
		category: 'Bag',
		description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, possimus nostrum!',
		price: 500,
		imageURL: 'https://www.leonardo.vn/cdn/shop/files/DSCF9037_700x.jpg?v=1697618326',
		buyQuantity: 0,
		remainingQuantity: 10,
	},
	{
		id: '6',
		name: 'Product 6',
		category: 'Bag',
		description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, possimus nostrum!',
		price: 600,
		imageURL: 'https://www.leonardo.vn/cdn/shop/products/balo-oxford-den-bags-leonardo-14032378986601_700x.jpg?v=1622169041',
		buyQuantity: 0,
		remainingQuantity: 10,
	},
];
